name: Deploy site to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 24.15.0

            - name: Install Dependencies
              run: npm ci

            - name: Build static files
              id: build
              run: npm run build

            - name: Upload static files as artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                  path: dist/

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
